<!--
	carbon:chevron-up — Carbon by IBM, Apache 2.0
	https://github.com/carbon-design-system/carbon/tree/main/packages/icons
	Generated by pnpm icons (scripts/icons.js): edit the list there, not this file.
-->
<script>
	let { ...props } = $props();
</script>

<svg xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 32 32" {...props}><path fill="currentColor" d="m16 10l10 10l-1.4 1.4l-8.6-8.6l-8.6 8.6L6 20z"/></svg>
