<!--
	carbon:chevron-down — Carbon by IBM, Apache 2.0
	https://github.com/carbon-design-system/carbon/tree/main/packages/icons
	Generated by pnpm icons (scripts/icons.js): edit the list there, not this file.
-->
<script>
	let { ...props } = $props();
</script>

<svg xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 32 32" {...props}><path fill="currentColor" d="M16 22L6 12l1.4-1.4l8.6 8.6l8.6-8.6L26 12z"/></svg>
