<!--
	carbon:close — Carbon by IBM, Apache 2.0
	https://github.com/carbon-design-system/carbon/tree/main/packages/icons
	Generated by pnpm icons (scripts/icons.js): edit the list there, not this file.
-->
<script>
	let { ...props } = $props();
</script>

<svg xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 32 32" {...props}><path fill="currentColor" d="M17.414 16L24 9.414L22.586 8L16 14.586L9.414 8L8 9.414L14.586 16L8 22.586L9.414 24L16 17.414L22.586 24L24 22.586z"/></svg>
