<!--
	carbon:filter — Carbon by IBM, Apache 2.0
	https://github.com/carbon-design-system/carbon/tree/main/packages/icons
	Generated by pnpm icons (scripts/icons.js): edit the list there, not this file.
-->
<script>
	let { ...props } = $props();
</script>

<svg xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 32 32" {...props}><path fill="currentColor" d="M18 28h-4a2 2 0 0 1-2-2v-7.59L4.59 11A2 2 0 0 1 4 9.59V6a2 2 0 0 1 2-2h20a2 2 0 0 1 2 2v3.59a2 2 0 0 1-.59 1.41L20 18.41V26a2 2 0 0 1-2 2M6 6v3.59l8 8V26h4v-8.41l8-8V6Z"/></svg>
