<!--
	carbon:close-large — Carbon by IBM, Apache 2.0
	https://github.com/carbon-design-system/carbon/tree/main/packages/icons
	Generated by pnpm icons (scripts/icons.js): edit the list there, not this file.
-->
<script>
	let { ...props } = $props();
</script>

<svg xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="0 0 32 32" {...props}><path fill="currentColor" d="M17.414 16L26 7.414L24.586 6L16 14.586L7.414 6L6 7.414L14.586 16L6 24.586L7.414 26L16 17.414L24.586 26L26 24.586z"/></svg>
