#!/usr/bin/env node

// Writes the icon components of src/lib/icons/ — one Svelte file per icon,
// fetched from the public Iconify API when this runs. The site ships the few
// icons it uses, and nothing else: it used to carry @iconify/json, 437 MB of
// node_modules for seventeen icons.
//
//   pnpm icons      regenerate every component from the list below
//
// To add an icon: find it on https://icon-sets.iconify.design, add its name
// under its set in ICONS, run pnpm icons, import the component. The markup is
// what unplugin-icons produced, attribute for attribute — width and height of
// 1.2em, the set's viewBox, every prop spread onto the <svg> — so
// `class="size-4"` and friends behave as before. Deterministic: running it
// again without editing the list leaves the files untouched.

import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ICONS = {
	carbon: [
		'arrow-right',
		'asleep',
		'chevron-down',
		'chevron-left',
		'chevron-right',
		'chevron-up',
		'close',
		'close-large',
		'document',
		'filter',
		'image',
		'menu',
		'star-filled',
		'sun'
	],
	'akar-icons': ['github-fill', 'instagram-fill', 'linkedin-fill']
};

const API = 'https://api.iconify.design';
const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'icons');

const componentName = (icon) =>
	'Icon' + icon.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());

async function fetchJson(url) {
	const res = await fetch(url, { headers: { 'user-agent': 'microfolio-icons' } });
	if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
	return res.json();
}

function component({ set, icon, data, info }) {
	const width = data.width ?? set.width ?? 16;
	const height = data.height ?? set.height ?? 16;
	const viewBox = `${data.left ?? 0} ${data.top ?? 0} ${width} ${height}`;
	return `<!--
	${set.prefix}:${icon} — ${info.name} by ${info.author.name}, ${info.license.title}
	${info.author.url}
	Generated by pnpm icons (scripts/icons.js): edit the list there, not this file.
-->
<script>
	let { ...props } = $props();
</script>

<svg xmlns="http://www.w3.org/2000/svg" width="1.2em" height="1.2em" viewBox="${viewBox}" {...props}>${data.body}</svg>
`;
}

function readme(sets) {
	const lines = [
		'# Icons',
		'',
		'Generated by `pnpm icons` (`scripts/icons.js`) from the public Iconify API — do not edit these files; edit the list in the script and run it again. Each component renders one SVG, `1.2em` square by default, and spreads its props onto it, so `<IconName class="size-4" />` sizes it like any element.',
		'',
		'| Component | Icon | Set | License |',
		'| --- | --- | --- | --- |'
	];
	for (const { set, info, icons } of sets) {
		for (const icon of icons) {
			lines.push(
				`| \`${componentName(icon)}\` | \`${set.prefix}:${icon}\` | [${info.name}](${info.author.url}) | ${info.license.title} |`
			);
		}
	}
	lines.push('', 'The sets, and their terms:', '');
	for (const { info } of sets) {
		lines.push(
			`- **${info.name}** by ${info.author.name} — ${info.license.title}${info.license.url ? ` (${info.license.url})` : ''}`
		);
	}
	return lines.join('\n') + '\n';
}

const prefixes = Object.keys(ICONS);
const collections = await fetchJson(`${API}/collections?prefixes=${prefixes.join(',')}`);

const sets = [];
for (const prefix of prefixes) {
	const icons = [...ICONS[prefix]].sort();
	const set = await fetchJson(`${API}/${prefix}.json?icons=${icons.join(',')}`);
	const missing = icons.filter((icon) => !set.icons[icon]);
	if (missing.length) throw new Error(`${prefix}: not served by the API — ${missing.join(', ')}`);
	sets.push({ set, info: collections[prefix], icons });
}

// Start clean, so an icon removed from the list disappears from the folder
await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

let count = 0;
for (const { set, info, icons } of sets) {
	for (const icon of icons) {
		const file = join(outDir, `${componentName(icon)}.svelte`);
		await writeFile(file, component({ set, icon, data: set.icons[icon], info }));
		count++;
	}
}
await writeFile(join(outDir, 'README.md'), readme(sets));

const written = (await readdir(outDir)).length;
console.log(`✓ ${count} icons → ${outDir} (${written} files)`);
